{{ if .Values.app.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing01
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.app.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-svc01
            port:
              number: {{ .Values.app.ports.web }}
  {{- if eq .Release.Namespace "weather02" }}           
  - host: weather02.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-svc01
            port:
              number: {{ .Values.app.ports.web }}
  {{ end }}
{{ end }}
