apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-quality-bot01
spec:
  strategy: 
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: weather-quality-bot
  template:
    metadata:
      labels:
        app: weather-quality-bot
    spec:
      containers:
      - name: app
        image: bazdoc/weather_app_bot:1.0
        ports:
        - containerPort: 8080
          name: web        
        envFrom:
          - secretRef:
              name: env-secret01
        volumeMounts:
        - name: template-volume
          mountPath: /template.txt
          subPath: template.txt
        readinessProbe:
          httpGet:
            path: /ready
            port: 8086
          initialDelaySeconds: 3
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /live
            port: 8086
          initialDelaySeconds: 3
          periodSeconds: 3     
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits: 
            cpu: 200m
            memory: 512Mi                           
      volumes:
      - name: template-volume
        configMap:
          name: cm01
