apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-quality-bot01
spec:
  strategy: 
    type: RollingUpdate
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: weather-quality-bot
  template:
    metadata:
      labels:
        app: weather-quality-bot
    spec:
      containers:
      - name: app
        image: bazdoc/weather_app_bot:1.0
        ports:
        - containerPort: {{ .Values.app.ports.web }}
          name: web        
        envFrom:
          - secretRef:
              name: env-secret01
        volumeMounts:
        - name: template-volume
          mountPath: /template.txt
          subPath: template.txt
 #       readinessProbe:
 #         httpGet:
 #           path: /ready
 #           port: {{ .Values.app.ports.probes}}
 #         initialDelaySeconds: 15
 #         periodSeconds: 600
 #       livenessProbe:
 #         httpGet:
 #           path: /live
 #           port: {{ .Values.app.ports.probes}}
 #         initialDelaySeconds: 3
 #         periodSeconds: 3     
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits: 
            cpu: 200m
            memory: 512Mi                           
      volumes:
      - name: template-volume
        configMap:
          name: cm01
