apiVersion: v1
kind: Secret
metadata:
  name: env-{{ .Release.Name }}
stringData:
  TG_TOKEN: "7797656775:AAF9L_HLZFr5SLQKlvbJ9IxCP-ElrF2iiCg"
  IQAIR_TOKEN: "d1b2ae91-0ff4-44e7-807e-d1e4eb5f3983"
  TEMPLATE_PATH: "/template.txt"
  CITY: moscow
  LOG_LEVEL: info # debug
