apiVersion: v1
kind: Service
metadata:
  name: weather-svc01
spec:
  selector:
    app: weather-quality-bot
  ports:
    - protocol: TCP
      port: {{ .Values.app.ports.web }}
      targetPort: {{ .Values.app.ports.web }}
